sameLine改为hContainer;添加vContainer,tContainer
jimmy-sketch/chen_cppcguilib pull request #17
Opened 2024-10-18 11:43 UTC by hnsk0808

sameLine改为hContainer，其中h是horizontal的缩写，代表水平容器
vContainer和tContainer中的v和t是vertical和table的缩写，代表竖直容器和表格容器

将logicPos.h移到了utils下面，改名为pos.h，添加了cgui namespace，以供tContainer使用
pos.h中还添加了Pos类型，表示实际位置，为新page作铺垫
pos在rol和col之外还多了一个深度，用来表示遮挡关系，0是最顶层，1会被0遮挡，2会被1遮挡...

修改page中的拼写错误，清理page中的无用代码，以及将page改写成tContainer实现（因为原先的逻辑和表格一摸一样）
对于以后的page，我打算把组件的位置改成实际位置而不是逻辑位置（如果要以前的page效果可以在page的0,0处插入一个tContainer）

为新组件修改了demo.cpp和readme文件

2024-10-19 05:07 UTC, jimmy-sketch reviewed
> 对于以后的page，我打算把组件的位置改成实际位置而不是逻辑位置（如果要以前的page效果可以在page的0,0处插入一个tContainer）

如果这么说的话，`page`将会作为内部组件使用，不对外公开？
也就是说，使用者可以创建一些水平/垂直/表格容器，然后将它们进行排版？
这个想法很有趣。

2024-10-19 13:57 UTC, jimmy-sketch commented on src/page.cpp
还是背离初衷了啊……
项目刚刚开始的时候还是争取一套代码走遍windows和linux了，现在又要搞大量移植了？

2024-10-19 14:04 UTC, hnsk0808 commented on src/page.cpp
目前的代码是支持linux，至少可以在wsl中正常运行

![image](https://github.com/user-attachments/assets/b33428b3-96de-403b-8b91-2e6ca511a4cc)

2024-10-19 14:09 UTC, hnsk0808 commented
这个pr对代码结构没有什么大的改动，总体的逻辑还是和以前一样的，没有改。

新添加了对utf8的支持，自适应窗口大小，还有解决窗口闪烁的问题，以及修复了一些bug。

2024-10-20 00:57 UTC, jimmy-sketch requested changes
这次更改我还有一些建议，烦请解决一下

2024-10-20 00:57 UTC, jimmy-sketch commented on include/cgui/components/hContainer.h
> +    void set(int col, std::shared_ptr<component> src);
关于这个我有个疑问，这里在容器内部自己管理col会不会更好？

2024-10-20 00:57 UTC, jimmy-sketch commented on include/cgui/components/vContainer.h
> +    void set(int row, std::shared_ptr<component> src);
跟上面`hContainer`是一个问题

2024-10-20 00:57 UTC, jimmy-sketch commented on include/cgui/utils/config.h
> +constexpr char paddingChar = '.';
记得加一个函数，可以选择改变它

2024-10-20 00:57 UTC, jimmy-sketch commented on include/cgui/utils/string.h
> +    // 如果结尾正好是某个Unicode符号的前半截，会得到<?>符号
其实根据一般的逻辑（或者正常的使用逻辑），那么一截应该是把一半的unicode符号的后一半给加上

2024-10-20 00:57 UTC, jimmy-sketch commented on include/cgui/utils/string.h
> -    void insertBackgroundRGB(int pos, int r, int g, int b);
这里的命名会不会有点怪？前面的追加是`append`，后面的怎么就成了`pushback `?

2024-10-20 00:57 UTC, jimmy-sketch commented on src/page.cpp
回头搞一点其他的发行版，或者android终端，我看看可不可以

2024-10-20 00:59 UTC, hnsk0808 commented on include/cgui/utils/string.h
> -    void insertBackgroundRGB(int pos, int r, int g, int b);
为了模仿std::string，标准库里pushBack是追加字符，而append是追加字符串

2024-10-20 01:02 UTC, hnsk0808 commented on include/cgui/utils/string.h
> +    // 如果结尾正好是某个Unicode符号的前半截，会得到<?>符号
这个函数最初是为了page的updata里对内容的截长补短用的，后一半加上去了就超过窗口限制了（可能会触发意料之外的换行），也许可以考虑丢弃最后一个不完整字符。

2024-10-20 01:12 UTC, hnsk0808 commented on include/cgui/components/hContainer.h
> +    void set(int col, std::shared_ptr<component> src);
"容器内部自己管理col"是怎么管理，是添加一个初始化列表来简化初始化操作，追加行用pushBack，行中间插入用insert吗？

2024-10-20 01:14 UTC, hnsk0808 commented on include/cgui/utils/config.h
> +constexpr char paddingChar = '.';
好的，那样的话就在头文件添加一个getPaddingChar和setPaddingChar，然后实现和char paddingChar;移到源文件里，可以吗？

2024-10-20 01:23 UTC, hnsk0808 commented on src/page.cpp
我觉得没什么问题，我查了一下cmake是可以生成安卓项目的，我之后尝试尝试。

2024-10-20 01:36 UTC, hnsk0808 commented on include/cgui/utils/string.h
> +    // 如果结尾正好是某个Unicode符号的前半截，会得到<?>符号
我又想了一下，这个函数本来设计的就是严格截取显示宽度为n的字符，对于占多个格子的字符中截一半的显示错误并不是错误，而是正常的行为，你要的功能应该放到一个新的函数里面吧。

2024-10-20 04:42 UTC, jimmy-sketch commented on include/cgui/components/hContainer.h
> +    void set(int col, std::shared_ptr<component> src);
> "容器内部自己管理col"是怎么管理，是添加一个初始化列表来简化初始化操作，追加行用pushBack，行中间插入用insert吗？

就是这样的。不然的话如果遇到某些粗心大意的就麻烦了

2024-10-20 04:43 UTC, jimmy-sketch commented on include/cgui/utils/string.h
> +    // 如果结尾正好是某个Unicode符号的前半截，会得到<?>符号
那好，那就这样做

2024-10-20 04:43 UTC, jimmy-sketch approved these changes

2024-10-20 14:02 UTC, hnsk0808 commented
按照建议对代码进行了修补。
增加了get/setPaddingChar，设置用来填充空白的字符。
增加了string::takeComplete，在take的基础上，返回的string总是完整的。
修改hContainer和vContainer，使其逻辑像std::vector一样（现在的set操作改成了用中括号[]，要注意索引不能超过其范围）。

2024-10-21 14:18 UTC, merged

2024-10-22 14:06 UTC, jimmy-sketch commented
以后我会开个issue，便于讨论新功能和改进……
至少统一一点，可以交换意见